### ISSUE TITLE
Add proxy configuration values to kernelspec

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-incubator/enterprise_gateway#161]
By extending the `process_proxy` stanza within the kernelspec, I think we could achieve some significant functional enhancements that make for a more flexible, finer-grained configuration.  The proposal would be to define a `proxy_config` stanza within `process_proxy` (and sibling to `class_name`) which contains a set of fields pertinent to the target process proxy class (and its super-classes).  Which fields are pertinent to which classes would need to be documented - along with their defaulted values (if not already).

A good example of this would be to have `yarn_endpoint` be a field that pertains to `YarnClusterProcessProxy`.  When present, kernels derived from that kernelspec would use that yarn endpoint for their activity.  This would allow administrators to utilize multiple Yarn clusters from a single Enterprise Gateway.

We could also do the same with remote hosts used to balance loads of `DistributedProcessProxy` kernels where sets of kernels are essentially assigned different sets of machines.

This would also allow greater flexibility to process proxy authors that require different (undetermined) kinds of information.

**Comment by lresende** [comment]
@kevin-bates aren't we done with this ?

**Comment by kevin-bates** [comment]
@lresende - no, this hasn't been implemented yet.
