### ISSUE TITLE
Investigate update of R launcher to use gateway communication port

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-incubator/enterprise_gateway#171]
This is related to issues #149 and #170 and PR #169 - which added support for a gateway communication port established by launchers.  This issue is to update the R launcher in a manner similar to how the python launcher was updated in #169.  If enabled (by default), the launcher needs to create a socket and return its port number in the connection info under the key `comm_port`.  It should then start a thread that listens on that port looking for json payloads with a `signum` key.  When received, it needs to send the parent thread the signal value.  

The problem with R is that its inherently a single-threaded language - so adding a listener thread may not be possible.  If this can't be achieved, then we'll need to document that R kernels running under different user ids than the gateway cannot be interrupted.

**Comment by kevin-bates** [comment]
I just stumbled upon this code in jupyter_client where it initializes a `kernelspec` and it refreshed my memory that there has been recent work to introduce a message-based interrupt into kernels:
```
    interrupt_mode = CaselessStrEnum(
        ['message', 'signal'], default_value='signal'
    )
```
As a result, we probably shouldn't spend our time breaking picks on multi-threading in R but perhaps see when/if IRkernel will/can support message-based interrupts.

**Comment by akchinSTC** [comment]
Looking thru the issues in IRkernel github, I dont see anything related to supporting message based interrupts so I will go ahead and open a new issue. Development looks a bit lethargic though, unless we decide on getting into kernel development ourselves, it may take a bit.
