### ISSUE TITLE
Cannot import a module that was pip installed from a cell

### ISSUE THREAD

**Issue by sanjay-saxena** [jupyter-incubator/enterprise_gateway#181]
I wanted to use `pixiedust` module in a notebook that is based on `Spark 2.1 - Python(YARN Client Mode)`. So, I tried to install `pixiedust` directly from the notebook cell as shown below:

```
!pip install --user --upgrade pixiedust
```
The log messages in the notebook indicated that `pixiedust` was installed successfully. I restarted the Kernel and when I tried to `import pixiedust` in another cell, I get the following error:

```
ImportError: No module named pixiedust
```

Here are my environment details:
1. NB2KG Server running locally on MacbookPro.
2. Enterprise Gateway(EG) version 0.7 Dev running on `ethan1.fyre.ibm.com`.
3. Create a new notebook for `Spark 2.1 - Python(YARN Client Mode)`. Based on the EG logs, the Kernel got launched on `ethan3.fyre.ibm.com`.
4. Run `!pip install --user --upgrade pixiedust` from the first cell.
5. Confirm whether `pixiedust` was  installed successfully by running `!pip list | grep pixiedust` from a cell.
6. Run `import pixiedust` from the next cell to see the aforementioned error.

The following image shows the issue:

![eg-pip](https://user-images.githubusercontent.com/7605221/31560731-5384f02a-b00a-11e7-80c6-f9567aecb570.png)

**Comment by sanjay-saxena** [comment]
It looks like `pixiedust` is installed in `ethan3.fyre.ibm.com` in `$USER/.local/lib/python-2.7/site-packages` folder. Perhaps, we need some java-esque `CLASSPATH` like mechanism to ensure that packages installed in `$USER/.local/lib/python-2.7/site-packages` are picked up by the Kernel.

**Comment by sanjay-saxena** [comment]
Maybe, `PYTHONPATH` specified in `kernel.json` needs to include the current-user's `~/.local/lib/python-2.7/site-packages` folder.

**Comment by ckadner** [comment]
I think the `--user` install is the problem here

**Comment by sanjay-saxena** [comment]
@ckadner suggested that I drop the `--user` switch while installing `pixiedust` using `!pip` from the notebook cell. Using a brand new notebook with Kernel running on a new node(`ethan4.fyre.ibm.com`),  I tried installing `pixiedust` without `--user` switch. This resulted in the following error:

```
OSError: [Errno 2] No such file or directory: '/opt/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg'
```

Then, @ckadner suggested that I first execute `!pip install setuptools`. This resulted in the following message:

```
Requirement already satisfied: setuptools in ./.local/lib/python2.7/site-packages
In [2]:
```

At this point, I re-installed `pixiedust` using `!pip install pixiedust`. And, the subsequent `import pixedust` ran successfully!

So, should we update our documentation to indicate that `--user` switch should not be used to install modules directly from the cell using the `!pip install` command?

**Comment by ckadner** [comment]
@lresende -- I suppose the `pip install setuptools` should be part of the Anaconda setup (via Ansible)

**Comment by sanjay-saxena** [comment]
Issues #191 and #192 will formalize the documentation that should address this issue.
