### ISSUE TITLE
Enterprise Gateway should be run under a non-root service user

### ISSUE THREAD

**Issue by sanjay-saxena** [jupyter-incubator/enterprise_gateway#191]
Enterprise Gateway's documentation should be augmented to include the fact that it **MUST** be run under a _non-root_ service user.

**Comment by kevin-bates** [comment]
@sanjay-saxena - thank you for raising this issue.  

I think it's too strong a statement to say Enterprise Gateway **MUST** be run by a non-root user.  I have no problem _strongly recommending_ that EG be started with a non-root user, but there's really nothing preventing a consumer to configure their system such that the root user is operational - although it's certainly not a best practice.

I'd prefer to add some discussion about service users and the remote user (used for the ssh operations) and how HDFS/YARN environments tend to treat user 'hdfs' as the authoritative user.  I will then add something like the following to the example start script...
```bash
if [ "$USER" = "root" ]; then
    echo "WARNING! Running Jupyter Enterprise Gateway as the 'root' user is not recommended!"
fi
```
Comments?

**Comment by sanjay-saxena** [comment]
@kevin-bates -- I am fine with it. I used *MUST* based on the conversation during Tuesday's scrum meeting where we talked about bailing with an error if the `$USER` is `root`.

**Comment by kevin-bates** [comment]
@sanjay-saxena - right, I understand.  After reflection, I just felt its not really our place to make that restriction.  I'm one that prefers to err on the side of _"Give them enough rope..."_.
