### ISSUE TITLE
Look into removing EG_REMOTE_USER and command-line option

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-incubator/enterprise_gateway#198]
TIL that running EG as one user and `EG_REMOTE_USER` pointing at a different user failed to startup (client-mode) kernels on remote hosts due to password-less ssh authentication failures - even when BOTH users are properly configured for ssh.  Since the default value for `EG_REMOTE_USER` is `$USER`, this suggests that we should drop `EG_REMOTE_USER` and its command line option (`--EnterpriseGatewayApp.remote_user`) and just let the "service user" be the "remote user" (as suggested in the [recent doc update](http://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started.html#service-and-remote-users)).

We could then just focus on using a non-root service user (also suggested in the recent update) and simplify things.  The ssh library already uses the current user as the default `username` anyway as well.

Documentation surrounding the remote user (and config options) will need to be removed or modified to reference the service or current user.

**Comment by sherryxg** [comment]
Will also need to update the Troubleshooting section with a new error.
