### ISSUE TITLE
Spark R client mode kernel's app name not same as kernel ID

### ISSUE THREAD

**Issue by liukun1016** [jupyter-incubator/enterprise_gateway#242]
Currently if a new Spark R client mode notebook is opened, and the SparkContext gets created, on the YARN RM UI side, the application name would be `SparkR` instead the kernel ID.

Here is an example: http://charger-master.fyre.ibm.com:8088/cluster/app/application_1512070656800_0072

**Comment by akchinSTC** [comment]
PR open
