### ISSUE TITLE
EG per kernel configuration question

### ISSUE THREAD

**Issue by charlie718y** [jupyter-incubator/enterprise_gateway#260]
Hi,

I've been trying to write up process_proxy, currently encountered a question regarding to "kernel specific" environment variables. 

From readthedoc, I notice the mentioning of "Per-kernel Configuration Overrides", however, from my understanding, this is set in the kernelspec "kernel.json" configuration file? Is that correct? 

I want to pass credential related parameters, is there a way not to put it in kernel.json and able to pass to the process_proxy?

Thanks,
Charlie

**Comment by kevin-bates** [comment]
@charlie718y - thanks for the question.
Yes, per kernel envs are typically static set in the kernel.json file.  However, to get more dynamic behavior, you'd want to override the `launch_process(kernel_cmd, **kw)` method.  `kw` is a dictionary of dictionaries, one of which is named `env`.  You would then add another entry in `kw['env']`.

Also note that if these credentialed values derive from the client side, the latest NB2KG will automatically "flow" all envs prefixed with `KERNEL_`.  Such env variables coming from the client are then automatically placed into `kw['env']`, so the method override would not be necessary (for these purposes).

**Comment by charlie718y** [comment]
@kevin-bates Hi Kevin,

Thanks for the quick reply. The latter sounds like what I need, since NB2KG is an extension to the Jupyter notebook, so that means, I have to get those env variables exported before launching the Jupyter notebook then. I will use this approach for now. Thanks again!
