### ISSUE TITLE
Encrypt kernel-startup negotiation

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-incubator/enterprise_gateway#262]
We currently send the connection info derived by the launcher back to enterprise gateway in clear text.  This information should be encrypted.

**Comment by sanjay-saxena** [comment]
Updated the title and the description of the issue as just `encoding` the initial handshake conversation between the Kernel Launchers and the Enterprise Gateway wouldn't satisfy the requirements for Enhanced Security.

Based on latest conversation, the initial handshake between the Kernel Launchers(Python, R, and Scala) and the Jupyter Enterprise Gateway would be encrypted using a symmetric-key algorithm such as AES whose implementation is not only readily available in all three languages/platforms but also works across cross-languages/platforms as the encryption and decryption may be happening in different languages/platforms.

**Comment by lresende** [comment]
This added **pycrypto 2.6.1** dependency which is compatible with our license.
