### ISSUE TITLE
Perform long-running ssh tunnneling integration tests

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-incubator/enterprise_gateway#263]

**Comment by akchinSTC** [comment]
Identified a need to test long running notebook sessions with SSH tunneling enabled between the gateway and the kernel. Test will consist of bringing up a new spark environment with an enterprise gateway as well as a notebook to test each of the three supported kernels over a period of 48 hours with random input from the notebook to simulate user activity.

**Comment by akchinSTC** [comment]
After working with the current itests that were previously setup, I would like to suggest moving the framework from unittest to pytest. Unittest will not readily accept command line arguments for dynamic testing without setup of some kind of driver in front, a custom test class constructor or use of environmental variables; pytest will and will also run unittests out of the box. 
Its also in use already in jupyter client and has an MIT license
