### ISSUE TITLE
Use Kubernetes as resource manager

### ISSUE THREAD

**Issue by elgalu** [jupyter-incubator/enterprise_gateway#287]
Feature request: Use Kubernetes as resource manager

**Comment by kevin-bates** [comment]
@elgalu - thank you for your request and interest!  We are immediately focused on getting our 0.8 release tied up, followed by some project management work.  You should then expect to see something relative to Kubernetes in 2-3 weeks.  Thanks.

**Comment by echarles** [comment]
Hello, are you progressing on the implementation? I am interested in helping based on my spark on k8s experience. If you have a PR, I can also help testing and give feedback,

**Comment by kevin-bates** [comment]
@elgalu and @echarles - again, thank you for your interest.  There are a few non-technical details that we must first tackle before we feel comfortable merging our branch into the repo.  We hope to have these worked out by the end of the month.  We apologize for the delay but look forward to working with you in the near future.

**Comment by echarles** [comment]
Thx @kevin-bates for the feedback. If the branch is public, I am happy to test it. Otherwise, hope you can fix the remaining issued soon.

**Comment by lresende** [comment]
@elgalu,  @echarles and all, The initial support for kubernetes is now available in the [kubernetes branch](https://github.com/jupyter-incubator/enterprise_gateway/tree/kubernetes). We plan to merge it to master in the next couple days.

**Comment by lresende** [comment]
We have merged Kubernetes support to Master branch.
