### ISSUE TITLE
Scala Kernel with Toree immediate Sparkcontext creation

### ISSUE THREAD

**Issue by charlieeeeeee** [jupyter-incubator/enterprise_gateway#300]
Hi,

I briefly talked with @kevin-bates about the JEG scala kernel support. The current behavior is scala kernel gets started by Apache Toree, and it uses the "deferred" Sparkcontext creation, and as user interact with the notebook, the Sparkcontext is later created. I'm wondering if it's possible for the scala kernel to behave similar to Python or R kernels where the launcher creates Sparkcontext immediately on startup.

Thanks,
Charlie

**Comment by lresende** [comment]
@charlieeeeeee could you please provide the spark_opts used to launch the scala kernel, particularly the one related to running in cluster mode.

**Comment by charlieeeeeee** [comment]
@lresende  Here's the spark-submit generated by the processproxy. Let me know what other information is needed.
 
spark-submit --master spark://hostname:6067 --conf spark.pyspark.python=/..../bin/python --name a2b13be4-9bff-4240-99c1-983343d85ab0 --jars /.../share/jupyter/kernels/spark_scala_conductor_cluster/lib/toree-assembly-0.2.0-incubating.jar --class launcher.ToreeLauncher /..../share/jupyter/kernels/spark_scala_conductor_cluster/lib/toree-launcher_2.11-0.8.0.SNAPSHOT.jar --profile /..../data/runtime/kernel-a2b13be4-9bff-4240-99c1-983343d85ab0.json --RemoteProcessProxy.response-address hostname:43906

**Comment by kevin-bates** [comment]
Closing.  This was addressed via [Toree PR 154](https://github.com/apache/incubator-toree/pull/154).  Thanks @lresende!
