### ISSUE TITLE
[Feature Request] R Kernel force evaluation on Sparkcontext creation

### ISSUE THREAD

**Issue by charlieeeeeee** [jupyter-incubator/enterprise_gateway#315]
Hey Guys,

I'm currently working on the Spark R kernel support. In the R kernel launcher code, all the contexts are lazily evaluated, as a result, the Sparkcontext will not be created unless it's being used/referenced. (Similar to the Apache Toree case) Is it possible to add something similar to Apache Toree, where we can create immediate Sparkcontext in the kernel launcher? Sorry for the inconvenience.

Thanks,
Charlie

**Comment by kevin-bates** [comment]
After a quick chat, we'll address this by introducing a new launcher option that indicates the *timeframe* for spark context initialization.  See Issue #316.

To address this change, we should go ahead and implement `eager` and `lazy` modes (with `lazy` being the current (and default) behavior).

**Comment by kevin-bates** [comment]
Addressed via PR #324 - closing issue.
