### ISSUE TITLE
Convey application name value via launcher option

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-incubator/enterprise_gateway#321]
@charlieeeeeee has run into an issue with the R launcher when running it in cluster mode on IBM Spectrum Conductor.  Since Spectrum Conductor doesn't have an option to convey the environment at runtime to the driver process and since SparkR appears to have an issue flowing the `--name` argument, the only way to get the application name into to the launcher is via an additional option to the launcher itself - since we know those can flow.  As a result, we need to create a new parameter that conveys the desired application name that the launcher can then set when creating the Spark context.

The name should be generic such that it could be used in other launchers (provided they have implemented its support) and other resource managers.  Some possible examples are: `--customAppName`, `--appNameOverride`, `--contextName`, ...

The value of this parameter would then be composed in the `run.sh` and set via `LAUNCH_OPTS`.  Its composition **must include** the value of `$KERNEL_ID`.

**Comment by charlieeeeeee** [comment]
@kevin-bates Thanks for the quick response. The suggested solution using parameter sounds good. 

Thanks again,
Charlie

**Comment by charlieeeeeee** [comment]
Also thanks @akchinSTC for evaluating the kernel_id restriction.
