### ISSUE TITLE
R Kernel startup contains error in Spark Driver

### ISSUE THREAD

**Issue by charlieeeeeee** [jupyter-incubator/enterprise_gateway#344]
Here's the Driver log,

Encrypted Payload: 
......
Warning message:
In if (!is.na(range)) { :
the condition has length > 1 and only the first element will be used
Spark package found in SPARK_HOME: /var/tmp/spark_home
Warning message:
'SparkR::sparkRSQL.init' is deprecated.
Use 'sparkR.session' instead.
See help("Deprecated") 
**Error in (function (x) : attempt to apply non-function**

Thanks,
Charlie

**Comment by akchinSTC** [comment]
The error occurs because of the initialize_spark_session function not taking in any arguments, as a small fix we pass in the initialization mode as an argument.
