### ISSUE TITLE
Update Conda Version?

### ISSUE THREAD

**Issue by bashterm** [jupyter-incubator/enterprise_gateway#406]
Condahub still is on version 0.9.3.

Is there a way I can upgrade that, or does a maintainer need to do that?

I have to use conda for this project, not pip.

Thanks!

**Comment by lresende** [comment]
Anaconda or Condahub is not a direct or transient dependency of Enterprise Gateway.
For information about conda package update, please see this [documentation page](https://conda.io/docs/user-guide/tasks/manage-pkgs.html).

**Comment by lresende** [comment]
Ok, @kevin-bates actually corrected me. You are looking for EG 9.4 on conda-forge, let me check that.

**Comment by lresende** [comment]
Ok, pushed the conda-forge changes and it should be there in a few minutes.
