### ISSUE TITLE
Enable to load kernels using entreprise_gateway?

### ISSUE THREAD

**Issue by ziedbouf** [jupyter-incubator/enterprise_gateway#431]
Thanks for this solution, we love the idea of connecting jupyter notebooks to spark cluster. I gone through the following [ansible playbook](https://github.com/lresende/ansible-spark-cluster/issues/14) and i was able to get the setup up and running on gcloud compute engine. Right now i am facing an issue while trying to connecting my jupyter notebook to the cluster `[W 21:49:37.661 NotebookApp] Error loading kernelspec 'python3'` and i am not able to catch what i am missing. I follow up the following instruction to connect my notebook:

`export KG_URL=http://spark-master:8888
export KG_HTTP_USER=elyra
export KG_HTTP_PASS=
export KG_REQUEST_TIMEOUT=30
export KERNEL_USERNAME=${KG_HTTP_USER}
jupyter notebook \
  --NotebookApp.session_manager_class=nb2kg.managers.SessionManager \
  --NotebookApp.kernel_manager_class=nb2kg.managers.RemoteKernelManager \
  --NotebookApp.kernel_spec_manager_class=nb2kg.managers.RemoteKernelSpecManager` 

Any help on this?

**Comment by kevin-bates** [comment]
@ziedbouf - thanks for taking EG for a spin. 

Given that `python3` is not one of the kernels we provide examples for and given the message is emanating from `NotebookApp` I'm inclined to believe this is more of a client-side issue, but your parameters look okay.  If you want, it might be worthwhile using the [elyra/nb2kg](https://hub.docker.com/r/elyra/nb2kg/) image for your client-side.  It is built from the [EG repo](https://github.com/jupyter-incubator/enterprise_gateway/tree/master/etc/docker/nb2kg) as well.

We will really need to see what, if anything, is happening in your EG server log.  A good first step is to perform a refresh from the Notebook "files view" - which will issue a request to retrieve the set of configured kernelspecs on the EG server.  This activity, and the kernelspecs EG detects, will appear in the EG logfile.

Since we don't provide examples for `python3`, you would need to configure a kernelspec similar to the examples we provide - where either `YarnClusterProcessProxy` or `DistributedProcessProxy` are configured in the kernelspec's `kernel.json` file, etc. in order to get the benefits of remote kernels.

If you're not using YARN, then you'd want to use the `DistributedProcessProxy`.  I just delivered a helpful PR yesterday in which I've added an [example kernelspec](https://github.com/kevin-bates/enterprise_gateway/tree/optimize-local-dpp/etc/kernelspecs/python_distributed) for how to launch a _vanilla_ python kernel using only `DistributedProcessProxy` - no relationship to spark is referenced.  However, for a spark cluster operation, you'd probably be best following the examples set forth in [`spark_python_yarn_client`](https://github.com/jupyter-incubator/enterprise_gateway/tree/master/etc/kernelspecs/spark_python_yarn_client).

Please post the EG log file when you get a chance and if you're still having issues after digesting the content above.

**Comment by lresende** [comment]
Copying updates from [here](https://github.com/lresende/ansible-spark-cluster/issues/25)

@ziedbouf Could you please attach more info from the logs: client (notebook) and server(gateway)
Also, are you using this with Spark Standalone? Have you installed NB2KG on the machine where you are running the notebook? 

Some other references might also help:
 - [enabling support for spark standalone](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-client-mode.html)
 - [Connecting Jupyter Notebook to Enterprise Gateway](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started.html#connecting-a-notebook-to-enterprise-gateway)

**Comment by ziedbouf** [comment]
Thanks @lresende  @kevin-bates 

I am using NB2KG on my client machine,  but it seems that it's not able to connect to the remote server(running on yarn mode). My approach to connect client to jupyter entreprise gateway is the following:

first start the jupyter entreprise extension on the server side:
`[elyra@spark-master bin]$ ps aux | grep jupyter
elyra    16950  7.6  0.1 304276 42596 pts/0    S    07:37   0:00 /opt/anaconda3/bin/python /opt/anaconda3/bin/jupyter-enterprisegateway --ip=0.0.0.0 --port=8888 --port_retries=0 --log-level=DEBUG --MappingKernelManager.cull_idle_timeout=600 --MappingKernelManager.cull_interval=30 --JupyterWebsocketPersonality.list_kernels=True
elyra    17336  0.0  0.0 112708   968 pts/0    S+   07:37   0:00 grep --color=auto jupyter
[elyra@spark-master bin]$ cat ../log/enterprise_gateway_2018-09-09.log 
[D 2018-09-09 07:37:19.736 EnterpriseGatewayApp] Searching ['/opt/elyra/bin', '/home/elyra/.jupyter', '/opt/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2018-09-09 07:37:19.737 EnterpriseGatewayApp] Looking for jupyter_config in /etc/jupyter
[D 2018-09-09 07:37:19.737 EnterpriseGatewayApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2018-09-09 07:37:19.737 EnterpriseGatewayApp] Looking for jupyter_config in /opt/anaconda3/etc/jupyter
[D 2018-09-09 07:37:19.737 EnterpriseGatewayApp] Looking for jupyter_config in /home/elyra/.jupyter
[D 2018-09-09 07:37:19.738 EnterpriseGatewayApp] Looking for jupyter_config in /opt/elyra/bin
[D 2018-09-09 07:37:19.738 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /etc/jupyter
[D 2018-09-09 07:37:19.739 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /usr/local/etc/jupyter
[D 2018-09-09 07:37:19.739 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /opt/anaconda3/etc/jupyter
[D 2018-09-09 07:37:19.739 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /home/elyra/.jupyter
[D 2018-09-09 07:37:19.739 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /opt/elyra/bin
[D 180909 07:37:19 selector_events:65] Using selector: EpollSelector
[I 2018-09-09 07:37:19.749 EnterpriseGatewayApp] Jupyter Enterprise Gateway at http://0.0.0.0:8888
`

Secondly i am using ssh port forwarding to map both local port on my machine:

`gcloud compute --project "test-project" ssh --zone "europe-west1-b" "spark-master" --ssh-flag="-L 8888:0.0.0.0:8888"`

I think i made a mistake in the above issue description by specifying the wrong host_name on `KG_URL=http://spark-master:8888` and changed to `KG_URL=http://127.0.0.1:8888` and this is my final config:

`export KG_URL=http://127.0.0.1:8888 export KG_HTTP_USER=elyra export KG_HTTP_PASS= export KG_REQUEST_TIMEOUT=30 export KERNEL_USERNAME=${KG_HTTP_USER} `

By running the jupyter notebook with jupyter entreprise extension, it seems to be fine but it's not catching kernel specs:

`jupyter notebook  --NotebookApp.session_manager_class=nb2kg.managers.SessionManager  --NotebookApp.kernel_manager_class=nb2kg.managers.RemoteKernelManager  --NotebookApp.kernel_spec_manager_class=nb2kg.managers.RemoteKernelSpecManager
[I 10:44:25.502 NotebookApp] The port 8888 is already in use, trying another port.
[I 10:44:25.509 NotebookApp] Serving notebooks from local directory: /Users/zied/Desktop/codebase/locations
[I 10:44:25.510 NotebookApp] The Jupyter Notebook is running at:
[I 10:44:25.510 NotebookApp] http://localhost:8889/?token=b7b0dae4e4e6297fe6a2d1a43f9f46abe9e88b4c5a8ac4ba
[I 10:44:25.510 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:44:25.511 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=b7b0dae4e4e6297fe6a2d1a43f9f46abe9e88b4c5a8ac4ba
[I 10:44:25.701 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 10:44:26.235 NotebookApp] Request kernel spec at: /api/kernelspecs/python3
[W 10:44:26.235 NotebookApp] Error loading kernelspec 'python3'
    Traceback (most recent call last):
      File "/Users/zied/Desktop/codebase/locations/env-3/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 267, in get_all_specs
        "spec": spec.to_dict()
    AttributeError: '_asyncio.Future' object has no attribute 'to_dict'
[I 10:45:42.711 NotebookApp] Request kernel spec at: /api/kernelspecs/python3
[W 10:45:42.712 NotebookApp] Error loading kernelspec 'python3'
    Traceback (most recent call last):
      File "/Users/zied/Desktop/codebase/locations/env-3/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 267, in get_all_specs
        "spec": spec.to_dict()
    AttributeError: '_asyncio.Future' object has no attribute 'to_dict'
[I 10:46:01.859 NotebookApp] New terminal with automatic name: 1
`

However the server side receive the call:
`
[elyra@spark-master ~]$ tail -f /opt/elyra/log/enterprise_gateway_2018-09-09.log 
[D 2018-09-09 07:37:19.737 EnterpriseGatewayApp] Looking for jupyter_config in /home/elyra/.jupyter
[D 2018-09-09 07:37:19.738 EnterpriseGatewayApp] Looking for jupyter_config in /opt/elyra/bin
[D 2018-09-09 07:37:19.738 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /etc/jupyter
[D 2018-09-09 07:37:19.739 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /usr/local/etc/jupyter
[D 2018-09-09 07:37:19.739 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /opt/anaconda3/etc/jupyter
[D 2018-09-09 07:37:19.739 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /home/elyra/.jupyter
[D 2018-09-09 07:37:19.739 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /opt/elyra/bin
[D 180909 07:37:19 selector_events:65] Using selector: EpollSelector
[I 2018-09-09 07:37:19.749 EnterpriseGatewayApp] Jupyter Enterprise Gateway at http://0.0.0.0:8888
[I 180909 07:44:26 web:2106] 200 GET /api/kernelspecs/python3 (127.0.0.1) 230.11ms
[I 180909 07:45:43 web:2106] 200 GET /api/kernelspecs/python3 (127.0.0.1) 2.29ms
`

**Comment by ziedbouf** [comment]
I am really sorry This is was stupid mistake from my side, i miss the installation step for NB2KG to activate the extension on client side:
`
jupyter serverextension enable --py nb2kg --sys-prefix
`

I feel so bad :(, thanks @lresende  and @kevin-bates for the support.

By the way is any examples on how to run pyspark while connecting the cluster to gcloud buckets, s3 etc....

**Comment by kevin-bates** [comment]
No worries - we're glad you're moving forward.

We only provide sample kernelspecs for HDP YARN, Spectrum Conductor and Kubernetes.  I would recommend that you take a look at `spark_python_yarn_cluster` and make the necessary modifications to get `spark-submit --master yarn --deploy-mode cluster`.  This will probably amount to adjusting path and file locations relative to the google gcloud deployment.

**Comment by ziedbouf** [comment]
Hi @kevin-bates 

i was trying to figure out this [issue-358365853](https://github.com/lresende/ansible-spark-cluster/issues/26#issue-358365853) for full day to get jupyter notebook submit the jobs to spark cluster with no success.
