### ISSUE TITLE
Re-instate --proxy-user in kernel files (enforce Kerberos)

### ISSUE THREAD

**Issue by ckadner** [jupyter-incubator/enterprise_gateway#50]
We temporarily removed the `--proxy-user ...` from the `etc/kernels/../kernel.json` files in PR #51.

We should re-instate the impersonation requirement once we have a working Kerberos setup and/or an install script to lay down the kernel files with an option to enable/disable impersonation with Kerberos.

**Comment by lresende** [comment]
Fixed in PR #235
